db:
  name: postgres
  username: postgres
  password: ENC(1kbI7+9ffycWCTBnvSd4Xw==:MtCRwMnSnK/x34jMH6rKYg==)
  host: 127.0.0.1
  port: 5432

instrument_and_token_schedule: True
golden_cross_schedule: True
